### ISSUE TITLE
IPV6 funktioniert nicht

### ISSUE THREAD

**Issue by getthemax** [va1entin/tools#1]
Ich habe jeweils einen Record für IPV4/IPV6 erstellt, mit einer IP die geändert werden soll
Wenn der IPV6 Eintrag geändert wird, wird dieser doppelt erstellt, und der IPV4 Eintrag gelöscht.

**Comment by va1entin** [comment]
Hi, danke für den Kommentar. Ich vermute es geht um `cloudflare-update-record`?

**Comment by getthemax** [comment]
Moin, richtig. Bei mir mit gh.domain.com getestet

**Comment by va1entin** [comment]
Das Problem sollte mit den Änderungen in ce08f26a420aba324f489256993eba559052b8c8 behoben sein.
Es trat auf, wenn es einen v4 und einen v6 Record mit dem gleichen Namen gab. Im Skript wird die ID des Records abgerufen, um ihn anschließend ändern zu können. Bisher wurde in diesem Request nicht zwischen v4 und v6 unterschieden sondern immer der erste genommen, den die Cloudflare API zurück gab.

@getthemax  Gerne mal testen :+1:

**Comment by getthemax** [comment]
Moin, klappt leider noch nicht bei mir:

`2022-02-04 18:43:08 INFO: Could not find file cloudflare-update-record_ip4.txt, continuing...
2022-02-04 18:43:10 ERROR: Could not find id of DNS record. "Results" in API response were empty. Please make sure that the specified DNS record already exists and config cloudflare-update-record_config.yaml is correct. Try again after. Dumping exception...
Traceback (most recent call last):
  File "/root/cloudflare-update-record/./cloudflare-update-record.py", line 108, in get_config
    config['record_identifier'] = record_id_response.json()['result'][0]['id']
IndexError: list index out of range`

`read_token: "jEK2..."
edit_token: "ppeh..."
zone_name: "domain.com"
record_name: "gh.domain.com"`

Beide Einträge sind da, und ich gehe davon aus das die Config richtig, zumindest lief es vorher damit

**Comment by va1entin** [comment]
Moin @getthemax
bitte einmal in der Config beim record_name `.domain.com` entfernen. Der record_name ist tatsächlich nur die Subdomain.
Mein Blog Post ist an der Stelle falsch, sorry dafür!

Klappt es dann?

Ich passe es dann an, dass beides funktioniert.

**Comment by getthemax** [comment]
Läuft super und vielen Dank

**Comment by va1entin** [comment]
Danke für das Feedback :+1: 
Mit 27765d8c6d6ea038a336d64652be9865ec27f832 habe ich einige Änderungen gemacht und Features eingebaut. U.a. wird die Config jetzt auf fehlende Parameter überprüft und darauf hingewiesen, wenn der `record_name` den `zone_name` enthält (zur Laufzeit wird das dann automatisch gefixt, sodass der Fehler nicht mehr auftritt - die Config wird nicht automatisch angepasst). Außerdem kann man jetzt die lokalen `ipvX.txt` Files ignorieren und es wird geprüft, ob die bei Cloudflare gesetzt IP mit der aktuellen übereinstimmt, bevor sie einfach gesetzt wird. Mit dem Force Parameter kann man sie trotz Übereinstimmung setzen.

Außerdem habe ich die Bindestriche im Namen durch Unterstriche ersetzt - inkl. der Default Config und Log File Location!
